services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
  scraping:
    build: https://github.com/aronkst/ruby-web-scraping.git#main
    environment:
      - APP_ENV=production
    ports:
      - 3001:3000
